[theme]
base = "dark"
primaryColor = "#E2A33D"
backgroundColor = "#131211"
secondaryBackgroundColor = "#232120"
textColor = "#EDEAE3"

[server]
headless = true
enableStaticServing = true

[browser]
gatherUsageStats = false
